name: 'Auto Release Daft'
description: 'Drafts a GitHub release with the changes introduced by a newly created version tag.'
author: 'Organization'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your outputs here.
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'

runs:
  using: node20
  main: dist/index.js
