name: Build
on:
    push:
        branches:
        - master
jobs:
    build:
        name: Build and Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
          - name: Get the sources
            uses: actions/checkout@v2
          - name: Restores the dependencies
            run: npm ci
          - name: Build
            run: npm run all